/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Answer = IDL.Record({
  'questionId' : QuestionId,
  'selectedOption' : IDL.Text,
});
export const ElectionId = IDL.Nat;
export const CastVoteArgs = IDL.Record({
  'answers' : IDL.Vec(Answer),
  'electionId' : ElectionId,
});
export const VoteConfirmation = IDL.Record({
  'electionId' : ElectionId,
  'confirmationToken' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const QuestionType = IDL.Variant({
  'multipleChoice' : IDL.Record({ 'options' : IDL.Vec(IDL.Text) }),
  'yesNo' : IDL.Null,
});
export const CreateQuestionArgs = IDL.Record({
  'text' : IDL.Text,
  'questionType' : QuestionType,
});
export const CreateElectionArgs = IDL.Record({
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'description' : IDL.Text,
  'questions' : IDL.Vec(CreateQuestionArgs),
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'questionType' : QuestionType,
});
export const Election = IDL.Record({
  'id' : ElectionId,
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const QuestionResult = IDL.Record({
  'optionCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'questionText' : IDL.Text,
  'questionId' : QuestionId,
});
export const ElectionResults = IDL.Record({
  'title' : IDL.Text,
  'eligibleVoterCount' : IDL.Nat,
  'totalVoters' : IDL.Nat,
  'questionResults' : IDL.Vec(QuestionResult),
  'electionId' : ElectionId,
  'turnoutPercent' : IDL.Float64,
});
export const TurnoutInfo = IDL.Record({
  'totalVotesCast' : IDL.Nat,
  'electionId' : ElectionId,
  'turnoutPercent' : IDL.Float64,
});
export const ElectionStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const ElectionSummary = IDL.Record({
  'id' : ElectionId,
  'startTime' : Timestamp,
  'status' : ElectionStatus,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'description' : IDL.Text,
  'questionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([CastVoteArgs], [VoteConfirmation], []),
  'createElection' : IDL.Func([CreateElectionArgs], [Election], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getElection' : IDL.Func([ElectionId], [IDL.Opt(Election)], ['query']),
  'getElectionResults' : IDL.Func(
      [ElectionId],
      [IDL.Opt(ElectionResults)],
      ['query'],
    ),
  'getTurnout' : IDL.Func([ElectionId], [IDL.Opt(TurnoutInfo)], ['query']),
  'hasVoted' : IDL.Func([ElectionId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveElections' : IDL.Func([], [IDL.Vec(ElectionSummary)], ['query']),
  'listElections' : IDL.Func([], [IDL.Vec(ElectionSummary)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Answer = IDL.Record({
    'questionId' : QuestionId,
    'selectedOption' : IDL.Text,
  });
  const ElectionId = IDL.Nat;
  const CastVoteArgs = IDL.Record({
    'answers' : IDL.Vec(Answer),
    'electionId' : ElectionId,
  });
  const VoteConfirmation = IDL.Record({
    'electionId' : ElectionId,
    'confirmationToken' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const QuestionType = IDL.Variant({
    'multipleChoice' : IDL.Record({ 'options' : IDL.Vec(IDL.Text) }),
    'yesNo' : IDL.Null,
  });
  const CreateQuestionArgs = IDL.Record({
    'text' : IDL.Text,
    'questionType' : QuestionType,
  });
  const CreateElectionArgs = IDL.Record({
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'description' : IDL.Text,
    'questions' : IDL.Vec(CreateQuestionArgs),
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'questionType' : QuestionType,
  });
  const Election = IDL.Record({
    'id' : ElectionId,
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const QuestionResult = IDL.Record({
    'optionCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'questionText' : IDL.Text,
    'questionId' : QuestionId,
  });
  const ElectionResults = IDL.Record({
    'title' : IDL.Text,
    'eligibleVoterCount' : IDL.Nat,
    'totalVoters' : IDL.Nat,
    'questionResults' : IDL.Vec(QuestionResult),
    'electionId' : ElectionId,
    'turnoutPercent' : IDL.Float64,
  });
  const TurnoutInfo = IDL.Record({
    'totalVotesCast' : IDL.Nat,
    'electionId' : ElectionId,
    'turnoutPercent' : IDL.Float64,
  });
  const ElectionStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'closed' : IDL.Null,
    'active' : IDL.Null,
  });
  const ElectionSummary = IDL.Record({
    'id' : ElectionId,
    'startTime' : Timestamp,
    'status' : ElectionStatus,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'description' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([CastVoteArgs], [VoteConfirmation], []),
    'createElection' : IDL.Func([CreateElectionArgs], [Election], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getElection' : IDL.Func([ElectionId], [IDL.Opt(Election)], ['query']),
    'getElectionResults' : IDL.Func(
        [ElectionId],
        [IDL.Opt(ElectionResults)],
        ['query'],
      ),
    'getTurnout' : IDL.Func([ElectionId], [IDL.Opt(TurnoutInfo)], ['query']),
    'hasVoted' : IDL.Func([ElectionId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveElections' : IDL.Func([], [IDL.Vec(ElectionSummary)], ['query']),
    'listElections' : IDL.Func([], [IDL.Vec(ElectionSummary)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };