/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : QuestionId, 'selectedOption' : string }
export interface CastVoteArgs {
  'answers' : Array<Answer>,
  'electionId' : ElectionId,
}
export interface CreateElectionArgs {
  'startTime' : Timestamp,
  'title' : string,
  'endTime' : Timestamp,
  'description' : string,
  'questions' : Array<CreateQuestionArgs>,
}
export interface CreateQuestionArgs {
  'text' : string,
  'questionType' : QuestionType,
}
export interface Election {
  'id' : ElectionId,
  'startTime' : Timestamp,
  'title' : string,
  'endTime' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
  'questions' : Array<Question>,
}
export type ElectionId = bigint;
export interface ElectionResults {
  'title' : string,
  'eligibleVoterCount' : bigint,
  'totalVoters' : bigint,
  'questionResults' : Array<QuestionResult>,
  'electionId' : ElectionId,
  'turnoutPercent' : number,
}
export type ElectionStatus = { 'scheduled' : null } |
  { 'closed' : null } |
  { 'active' : null };
export interface ElectionSummary {
  'id' : ElectionId,
  'startTime' : Timestamp,
  'status' : ElectionStatus,
  'title' : string,
  'endTime' : Timestamp,
  'description' : string,
  'questionCount' : bigint,
}
export interface Question {
  'id' : QuestionId,
  'text' : string,
  'questionType' : QuestionType,
}
export type QuestionId = bigint;
export interface QuestionResult {
  'optionCounts' : Array<[string, bigint]>,
  'questionText' : string,
  'questionId' : QuestionId,
}
export type QuestionType = {
    'multipleChoice' : { 'options' : Array<string> }
  } |
  { 'yesNo' : null };
export type Timestamp = bigint;
export interface TurnoutInfo {
  'totalVotesCast' : bigint,
  'electionId' : ElectionId,
  'turnoutPercent' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoteConfirmation {
  'electionId' : ElectionId,
  'confirmationToken' : string,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[CastVoteArgs], VoteConfirmation>,
  'createElection' : ActorMethod<[CreateElectionArgs], Election>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getElection' : ActorMethod<[ElectionId], [] | [Election]>,
  'getElectionResults' : ActorMethod<[ElectionId], [] | [ElectionResults]>,
  'getTurnout' : ActorMethod<[ElectionId], [] | [TurnoutInfo]>,
  'hasVoted' : ActorMethod<[ElectionId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveElections' : ActorMethod<[], Array<ElectionSummary>>,
  'listElections' : ActorMethod<[], Array<ElectionSummary>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];