/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CastVoteArgs {
    answers: Array<Answer>;
    electionId: ElectionId;
}
export interface TurnoutInfo {
    totalVotesCast: bigint;
    electionId: ElectionId;
    turnoutPercent: number;
}
export type Timestamp = bigint;
export type QuestionType = {
    __kind__: "multipleChoice";
    multipleChoice: {
        options: Array<string>;
    };
} | {
    __kind__: "yesNo";
    yesNo: null;
};
export interface ElectionResults {
    title: string;
    eligibleVoterCount: bigint;
    totalVoters: bigint;
    questionResults: Array<QuestionResult>;
    electionId: ElectionId;
    turnoutPercent: number;
}
export type ElectionId = bigint;
export type QuestionId = bigint;
export interface VoteConfirmation {
    electionId: ElectionId;
    confirmationToken: string;
}
export interface QuestionResult {
    optionCounts: Array<[string, bigint]>;
    questionText: string;
    questionId: QuestionId;
}
export interface CreateElectionArgs {
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    description: string;
    questions: Array<CreateQuestionArgs>;
}
export interface CreateQuestionArgs {
    text: string;
    questionType: QuestionType;
}
export interface Answer {
    questionId: QuestionId;
    selectedOption: string;
}
export interface ElectionSummary {
    id: ElectionId;
    startTime: Timestamp;
    status: ElectionStatus;
    title: string;
    endTime: Timestamp;
    description: string;
    questionCount: bigint;
}
export interface Question {
    id: QuestionId;
    text: string;
    questionType: QuestionType;
}
export interface Election {
    id: ElectionId;
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    createdBy: Principal;
    description: string;
    questions: Array<Question>;
}
export enum ElectionStatus {
    scheduled = "scheduled",
    closed = "closed",
    active = "active"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    castVote(args: CastVoteArgs): Promise<VoteConfirmation>;
    createElection(args: CreateElectionArgs): Promise<Election>;
    getCallerUserRole(): Promise<UserRole>;
    getElection(id: ElectionId): Promise<Election | null>;
    getElectionResults(electionId: ElectionId): Promise<ElectionResults | null>;
    getTurnout(electionId: ElectionId): Promise<TurnoutInfo | null>;
    hasVoted(electionId: ElectionId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listActiveElections(): Promise<Array<ElectionSummary>>;
    listElections(): Promise<Array<ElectionSummary>>;
}
import type { CreateElectionArgs as _CreateElectionArgs, CreateQuestionArgs as _CreateQuestionArgs, Election as _Election, ElectionId as _ElectionId, ElectionResults as _ElectionResults, ElectionStatus as _ElectionStatus, ElectionSummary as _ElectionSummary, Question as _Question, QuestionId as _QuestionId, QuestionType as _QuestionType, Timestamp as _Timestamp, TurnoutInfo as _TurnoutInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async castVote(arg0: CastVoteArgs): Promise<VoteConfirmation> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0);
            return result;
        }
    }
    async createElection(arg0: CreateElectionArgs): Promise<Election> {
        if (this.processError) {
            try {
                const result = await this.actor.createElection(to_candid_CreateElectionArgs_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Election_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createElection(to_candid_CreateElectionArgs_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Election_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElection(arg0: ElectionId): Promise<Election | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getElection(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElection(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getElectionResults(arg0: ElectionId): Promise<ElectionResults | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getElectionResults(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElectionResults(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTurnout(arg0: ElectionId): Promise<TurnoutInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurnout(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurnout(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasVoted(arg0: ElectionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVoted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVoted(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveElections(): Promise<Array<ElectionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveElections();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveElections();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listElections(): Promise<Array<ElectionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listElections();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listElections();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ElectionStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElectionStatus): ElectionStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ElectionSummary_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ElectionSummary): ElectionSummary {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Election_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Election): Election {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Election]): Election | null {
    return value.length === 0 ? null : from_candid_Election_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ElectionResults]): ElectionResults | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TurnoutInfo]): TurnoutInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ElectionId;
    startTime: _Timestamp;
    title: string;
    endTime: _Timestamp;
    createdBy: Principal;
    description: string;
    questions: Array<_Question>;
}): {
    id: ElectionId;
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    createdBy: Principal;
    description: string;
    questions: Array<Question>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        createdBy: value.createdBy,
        description: value.description,
        questions: from_candid_vec_n12(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    text: string;
    questionType: _QuestionType;
}): {
    id: QuestionId;
    text: string;
    questionType: QuestionType;
} {
    return {
        id: value.id,
        text: value.text,
        questionType: from_candid_QuestionType_n15(_uploadFile, _downloadFile, value.questionType)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ElectionId;
    startTime: _Timestamp;
    status: _ElectionStatus;
    title: string;
    endTime: _Timestamp;
    description: string;
    questionCount: bigint;
}): {
    id: ElectionId;
    startTime: Timestamp;
    status: ElectionStatus;
    title: string;
    endTime: Timestamp;
    description: string;
    questionCount: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_ElectionStatus_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endTime: value.endTime,
        description: value.description,
        questionCount: value.questionCount
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    multipleChoice: {
        options: Array<string>;
    };
} | {
    yesNo: null;
}): {
    __kind__: "multipleChoice";
    multipleChoice: {
        options: Array<string>;
    };
} | {
    __kind__: "yesNo";
    yesNo: null;
} {
    return "multipleChoice" in value ? {
        __kind__: "multipleChoice",
        multipleChoice: value.multipleChoice
    } : "yesNo" in value ? {
        __kind__: "yesNo",
        yesNo: value.yesNo
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    closed: null;
} | {
    active: null;
}): ElectionStatus {
    return "scheduled" in value ? ElectionStatus.scheduled : "closed" in value ? ElectionStatus.closed : "active" in value ? ElectionStatus.active : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ElectionSummary>): Array<ElectionSummary> {
    return value.map((x)=>from_candid_ElectionSummary_n23(_uploadFile, _downloadFile, x));
}
function to_candid_CreateElectionArgs_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateElectionArgs): _CreateElectionArgs {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateQuestionArgs_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateQuestionArgs): _CreateQuestionArgs {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    description: string;
    questions: Array<CreateQuestionArgs>;
}): {
    startTime: _Timestamp;
    title: string;
    endTime: _Timestamp;
    description: string;
    questions: Array<_CreateQuestionArgs>;
} {
    return {
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        description: value.description,
        questions: to_candid_vec_n5(_uploadFile, _downloadFile, value.questions)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    questionType: QuestionType;
}): {
    text: string;
    questionType: _QuestionType;
} {
    return {
        text: value.text,
        questionType: to_candid_QuestionType_n8(_uploadFile, _downloadFile, value.questionType)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "multipleChoice";
    multipleChoice: {
        options: Array<string>;
    };
} | {
    __kind__: "yesNo";
    yesNo: null;
}): {
    multipleChoice: {
        options: Array<string>;
    };
} | {
    yesNo: null;
} {
    return value.__kind__ === "multipleChoice" ? {
        multipleChoice: value.multipleChoice
    } : value.__kind__ === "yesNo" ? {
        yesNo: value.yesNo
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CreateQuestionArgs>): Array<_CreateQuestionArgs> {
    return value.map((x)=>to_candid_CreateQuestionArgs_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
